<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GC - <?php echo "teste"?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>

<body class="container bg-dark">
    <header>
        <nav class='navbar bg-light bg-opacity-50 navbar-expand-md mt-2 rounded border'>
            <div class="container-fluid">
                <a href="/" class="navbar-brand text-dark strong fw-bold fs-2">Gerenciador de chamados</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menu" aria-controls="#menu" aria-expanded="false" aria-label="Menu">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="menu" class="container">
                    <ul class="nav ms-auto me-2 d-block d-md-flex list-group list-group-horizontal rounded row">

                        <li class="nav-item list-group-item p-0 bg-success col-md-2 text-nowrap overflow-hidden text-center">
                            <a href="/new_ticket" class="nav-link  text-light "><i class="fas fa-plus"></i></a>
                        </li>

                        <li class="nav-item list-group-item p-0 bg-success bg-opacity-50 col-md-4 m-0 text-nowrap overflow-hidden text-lg-center">
                            <a href="/panel" class="nav-link m-0 ps-1 pe-1 fw-bold text-light fs-6 ">Consultar tickets</a>
                        </li>
                        <li class="nav-item col-md-5 m-0 p-0 text-center">
                            <form class="d-flex" id="searchForm" role="search" method="get" action="/edit_ticket">
                                <input class="m-0 list-group-item form-control rounded-0 bg-primary bg-opacity-25 text-center  text-light " type="search" placeholder="Nº ticket" aria-label="Search" name="id">
                                <button class="m-0 list-group-item bg-primary text-light" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </form>
                        </li>
                        <li class="nav-item col-md-1 m-0 p-0">
                            <a href="/logout" class="m-0 ps-md-2 ps-lg-3 list-group-item rounded-end bg-danger text-light">
                                <i class="fas fa-sign-out-alt"></i>
                            </a>
                        </li>
                    </ul>


                </div>
            </div>
        </nav>
        <div class="row justify-content-end m-0 p-0 me-5">
            <div id="divMessage" class="alert alert-dismissible fade show mt-2 m-0 p-0 fs-6 col-10 col-md-4 bg-danger bg-opacity-25" role="alert" hidden>
                <p id="message" class="m-0 p-0 ps-1">Ticket não encontrado</p>
                <button id="closeMessage" type="button" class="btn-close m-0 p-0 pe-1 pt-1" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </header>

    <article>
        <?= $this->contents() ?>
    </article>

    <footer class="row" id="rodape">
        <hr>

    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>